<?php
// src/Codopenex/ClinicianBaseBundle/Repository/MedicalFacilityRepository.php

namespace Codopenex\ClinicianBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedicalFacilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom !ACTUALLY IT WASN'T - NEED TO LOOK INTO WHY DOCTRINE NOT GENERATING!
 * repository methods below.
 */
class MedicalFacilityRepository extends EntityRepository
{
	public function getMedicalFacilities()
	{
		$medical_facilities = $this->createQueryBuilder('m')
						 ->select('m')
						 ->getQuery()
						 ->getResult();
	
		return $medical_facilities;
	}
	
}