<?php
// src/Codopenex/ClinicianBaseBundle/Repository/SpecialtyRepository.php

namespace Codopenex\ClinicianBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialtyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom !ACTUALLY IT WASN'T - NEED TO LOOK INTO WHY DOCTRINE NOT GENERATING!
 * repository methods below.
 */
class SpecialtyRepository extends EntityRepository
{
	public function getSpecialties()
	{
		$specialties = $this->createQueryBuilder('s')
						 ->select('s')
						 ->getQuery()
						 ->getResult();
	
		return $specialties;
	}
	
}